#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : ebaz4205.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Tue Aug 08 22:09:56 CEST 2023
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# Tool Version Limit: 2022.10 
#
# usage: ebaz4205.sh [-help]
# usage: ebaz4205.sh [-lib_map_path]
# usage: ebaz4205.sh [-noclean_files]
# usage: ebaz4205.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'ebaz4205.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Set vlogan compile options
vlogan_opts="-full64 "

# Set vhdlan compile options
vhdlan_opts="-full64 "

# Set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc+pp+dmptf -t ps -licqueue -l elaborate.log "

# Set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log "

# Design libraries
design_libs=(xilinx_vip xpm xlslice_v1_0_2 xil_defaultlib xlconcat_v2_1_4 xlconstant_v1_1_7 lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 axi_infrastructure_v1_1_0 axi_vip_v1_1_13 processing_system7_vip_v1_0_15 xbip_utils_v3_0_10 c_reg_fd_v12_0_6 xbip_dsp48_wrapper_v3_0_4 xbip_pipe_v3_0_6 xbip_dsp48_addsub_v3_0_6 xbip_addsub_v3_0_6 c_addsub_v12_0_14 axi_utils_v2_0_6 xbip_bram18k_v3_0_6 mult_gen_v12_0_18 xbip_dsp48_multadd_v3_0_6 dds_compiler_v6_0_22 axi_lite_ipif_v3_0_4 interrupt_control_v3_1_4 axi_gpio_v2_0_29 cic_compiler_v4_0_16 fir_compiler_v7_2_18 util_vector_logic_v2_0_2 lib_pkg_v1_0_2 fifo_generator_v13_2_7 lib_fifo_v1_0_16 blk_mem_gen_v8_4_5 lib_bmg_v1_0_14 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_29 axi_vdma_v6_3_15 axis_infrastructure_v1_1_0 axis_register_slice_v1_1_27 axis_subset_converter_v1_1_27 v_tc_v6_2_5 v_tc_v6_1_13 v_vid_in_axi4s_v4_0_9 v_axi4s_vid_out_v4_0_15 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_27 axi_data_fifo_v2_1_26 axi_crossbar_v2_1_28 audio_formatter_v1_0_9 i2s_receiver_v1_0_5 axi_protocol_converter_v2_1_27 axi_clock_converter_v2_1_26 axi_dwidth_converter_v2_1_27)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "ebaz4205.sh - Script generated by export_simulation (Vivado v2022.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "/tools/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/tools/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlslice_v1_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/11d0/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_xlslice_0_0/sim/ebaz4205_xlslice_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_xlconcat_0_0/sim/ebaz4205_xlconcat_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/badb/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_xlconstant_0_2/sim/ebaz4205_xlconstant_0_2.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_DivideBy2N_0_0/sim/ebaz4205_DivideBy2N_0_0.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_DivideBy4_25MHz_0/sim/ebaz4205_DivideBy4_25MHz_0.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_clk_wiz_0_0/ebaz4205_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_clk_wiz_0_0/ebaz4205_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_proc_sys_reset_0_0/sim/ebaz4205_proc_sys_reset_0_0.vhd" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_proc_sys_reset_0_1/sim/ebaz4205_proc_sys_reset_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_13 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ffc2/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_15 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_processing_system7_0_0/sim/ebaz4205_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_rst_ENET0_GMII_RX_CLK_0_100M_0/sim/ebaz4205_rst_ENET0_GMII_RX_CLK_0_100M_0.vhd" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_rst_ps7_0_140M_0/sim/ebaz4205_rst_ps7_0_140M_0.vhd" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_rst_ps7_0_64M_0/sim/ebaz4205_rst_ps7_0_64M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_clk_wiz_0_2/ebaz4205_clk_wiz_0_2_clk_wiz.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_clk_wiz_0_2/ebaz4205_clk_wiz_0_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_proc_sys_reset_0_4/sim/ebaz4205_proc_sys_reset_0_4.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_xlconcat_1_0/sim/ebaz4205_xlconcat_1_0.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_xlconcat_2_0/sim/ebaz4205_xlconcat_2_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/364f/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_reg_fd_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/edec/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/cdbf/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7468/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/910d/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/cfdd/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_addsub_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ebb8/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_c_addsub_0_1/sim/ebaz4205_c_addsub_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_xlslice_1_0/sim/ebaz4205_xlslice_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_utils_v2_0_6 $vhdlan_opts \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/1971/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/d367/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_18 $vhdlan_opts \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ab19/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_multadd_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/b0ac/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work dds_compiler_v6_0_22 $vhdlan_opts \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/a99f/hdl/dds_compiler_v6_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_dds_compiler_0_0/sim/ebaz4205_dds_compiler_0_0.vhd" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_dds_compiler_0_2/sim/ebaz4205_dds_compiler_0_2.vhd" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_mult_gen_0_2/sim/ebaz4205_mult_gen_0_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_xlconstant_2_3/sim/ebaz4205_xlconstant_2_3.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_xlconstant_3_0/sim/ebaz4205_xlconstant_3_0.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_dds_axi_interface_0_2/sim/ebaz4205_dds_axi_interface_0_2.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_xlconstant_0_6/sim/ebaz4205_xlconstant_0_6.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_29 $vhdlan_opts \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/6219/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_axi_gpio_1_0/sim/ebaz4205_axi_gpio_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_xlconstant_0_0/sim/ebaz4205_xlconstant_0_0.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_xlconstant_1_0/sim/ebaz4205_xlconstant_1_0.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_xlconstant_2_0/sim/ebaz4205_xlconstant_2_0.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_axis_mux_0_0/sim/ebaz4205_axis_mux_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_RF_test_1MHz_0/sim/ebaz4205_RF_test_1MHz_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_xlconstant_2_1/sim/ebaz4205_xlconstant_2_1.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_dds_axi_interface_0_0/sim/ebaz4205_dds_axi_interface_0_0.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_xlslice_sin_0/sim/ebaz4205_xlslice_sin_0.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_xlslice_0_3/sim/ebaz4205_xlslice_0_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_mult_gen_0_0/sim/ebaz4205_mult_gen_0_0.vhd" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_mult_sin_0/sim/ebaz4205_mult_sin_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_xlslice_0_4/sim/ebaz4205_xlslice_0_4.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_c_addsub_0_0/sim/ebaz4205_c_addsub_0_0.vhd" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_mult_gen_0_1/sim/ebaz4205_mult_gen_0_1.vhd" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_mult_gen_1_0/sim/ebaz4205_mult_gen_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_sqrt32_0_0/sim/ebaz4205_sqrt32_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_dds_compiler_0_6/sim/ebaz4205_dds_compiler_0_6.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_xlslice_0_10/sim/ebaz4205_xlslice_0_10.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_xlslice_0_11/sim/ebaz4205_xlslice_0_11.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work cic_compiler_v4_0_16 $vhdlan_opts \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/5400/hdl/cic_compiler_v4_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_cic_compiler_0_0/sim/ebaz4205_cic_compiler_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work fir_compiler_v7_2_18 $vhdlan_opts \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/d172/hdl/fir_compiler_v7_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_fir_compiler_0_0/sim/ebaz4205_fir_compiler_0_0.vhd" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_mult_gen_0_3/sim/ebaz4205_mult_gen_0_3.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_axi_interface_DEC_RATE_Q_0/sim/ebaz4205_axi_interface_DEC_RATE_Q_0.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_axis2c_combine_0_0/sim/ebaz4205_axis2c_combine_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_axi_gpio_0_1/sim/ebaz4205_axi_gpio_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_axis2c_splitter_0_4/sim/ebaz4205_axis2c_splitter_0_4.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_DivideBy10_0/sim/ebaz4205_DivideBy10_0.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_xlconstant_0_7/sim/ebaz4205_xlconstant_0_7.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_xlconstant_0_8/sim/ebaz4205_xlconstant_0_8.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_DivideBy2N_0_1/sim/ebaz4205_DivideBy2N_0_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work util_vector_logic_v2_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/3d84/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_util_vector_logic_0_2/sim/ebaz4205_util_vector_logic_0_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_dds_compiler_0_5/sim/ebaz4205_dds_compiler_0_5.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_xlslice_0_9/sim/ebaz4205_xlslice_0_9.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_xlslice_1_3/sim/ebaz4205_xlslice_1_3.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_i2s_transmitter_16_0_0/sim/ebaz4205_i2s_transmitter_16_0_0.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_util_vector_logic_0_3/sim/ebaz4205_util_vector_logic_0_3.v" \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/9097/src/mmcme2_drp.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/9097/src/axi_dynclk_S00_AXI.vhd" \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/9097/src/axi_dynclk.vhd" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_axi_dynclk_0_0/sim/ebaz4205_axi_dynclk_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/83df/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_7 $vhdlan_opts \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/83df/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/83df/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_16 $vhdlan_opts \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/6c82/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/25a8/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_bmg_v1_0_14 $vhdlan_opts \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/3a3e/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_29 $vhdlan_opts \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/2237/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_vdma_v6_3_15 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl/axi_vdma_v6_3_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_vdma_v6_3_15 $vhdlan_opts \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl/axi_vdma_v6_3_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_axi_vdma_0_0/sim/ebaz4205_axi_vdma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_register_slice_v1_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/6ba3/hdl/axis_register_slice_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_axis_subset_converter_0_0/hdl/tdata_ebaz4205_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_axis_subset_converter_0_0/hdl/tuser_ebaz4205_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_axis_subset_converter_0_0/hdl/tstrb_ebaz4205_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_axis_subset_converter_0_0/hdl/tkeep_ebaz4205_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_axis_subset_converter_0_0/hdl/tid_ebaz4205_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_axis_subset_converter_0_0/hdl/tdest_ebaz4205_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_axis_subset_converter_0_0/hdl/tlast_ebaz4205_axis_subset_converter_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_subset_converter_v1_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/40cb/hdl/axis_subset_converter_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_axis_subset_converter_0_0/hdl/top_ebaz4205_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_axis_subset_converter_0_0/sim/ebaz4205_axis_subset_converter_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work v_tc_v6_2_5 $vhdlan_opts \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/399a/hdl/v_tc_v6_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_v_tc_0_0/sim/ebaz4205_v_tc_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_xlconstant_0_3/sim/ebaz4205_xlconstant_0_3.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_xlconcat_0_3/sim/ebaz4205_xlconcat_0_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work v_tc_v6_1_13 $vhdlan_opts \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/b92e/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_vid_in_axi4s_v4_0_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/b2aa/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_axi4s_vid_out_v4_0_15 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/1b6c/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_v_axi4s_vid_out_0_1/sim/ebaz4205_v_axi4s_vid_out_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/d3fb/src/DVI_Constants.vhd" \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/d3fb/src/OutputSERDES.vhd" \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/d3fb/src/TMDS_Encoder.vhd" \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/d3fb/src/rgb2dvi.vhd" \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/d3fb/src/ClockGen.vhd" \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/d3fb/src/SyncAsync.vhd" \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/d3fb/src/SyncAsyncReset.vhd" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_rgb2dvi_0_3/sim/ebaz4205_rgb2dvi_0_3.vhd" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_axi_gpio_0_2/sim/ebaz4205_axi_gpio_0_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/f0b4/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/3111/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_28 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/c40e/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_xbar_0/sim/ebaz4205_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_mult_gen_0_4/sim/ebaz4205_mult_gen_0_4.vhd" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_mult_gen_1_1/sim/ebaz4205_mult_gen_1_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_xlslice_0_5/sim/ebaz4205_xlslice_0_5.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_xlslice_1_1/sim/ebaz4205_xlslice_1_1.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_xlslice_2_0/sim/ebaz4205_xlslice_2_0.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_dds_axi_interface_0_3/sim/ebaz4205_dds_axi_interface_0_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_dds_compiler_0_3/sim/ebaz4205_dds_compiler_0_3.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_xlconstant_0_4/sim/ebaz4205_xlconstant_0_4.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_dds_axi_interface_0_4/sim/ebaz4205_dds_axi_interface_0_4.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_cic_compiler_0_1/sim/ebaz4205_cic_compiler_0_1.vhd" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_fir_compiler_0_1/sim/ebaz4205_fir_compiler_0_1.vhd" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_mult_gen_0_5/sim/ebaz4205_mult_gen_0_5.vhd" \
    "$ref_dir/../../../bd/ebaz4205/ipshared/afb0/dp_ram_1r_1w_2clk.vhd" \
    "$ref_dir/../../../bd/ebaz4205/ipshared/afb0/axis_capture_logic.vhd" \
    "$ref_dir/../../../bd/ebaz4205/ipshared/afb0/axis_capture.vhd" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_axis_capture_0_5/sim/ebaz4205_axis_capture_0_5.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_xlconcat_0_4/sim/ebaz4205_xlconcat_0_4.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_axis2c_combine_0_1/sim/ebaz4205_axis2c_combine_0_1.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_reset_lengthener_0_0/sim/ebaz4205_reset_lengthener_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_axi_gpio_0_5/sim/ebaz4205_axi_gpio_0_5.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_axis2c_splitter_0_2/sim/ebaz4205_axis2c_splitter_0_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ebaz4205/ipshared/9b21/src/debounce.vhd" \
    "$ref_dir/../../../bd/ebaz4205/ipshared/9b21/src/ps2_transceiver.vhd" \
    "$ref_dir/../../../bd/ebaz4205/ipshared/9b21/src/ps2_mouse_w.vhd" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_ps2_mouse_0_0/sim/ebaz4205_ps2_mouse_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_util_vector_logic_0_1/sim/ebaz4205_util_vector_logic_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_axi_gpio_0_3/sim/ebaz4205_axi_gpio_0_3.vhd" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_axi_gpio_0_4/sim/ebaz4205_axi_gpio_0_4.vhd" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_axis_capture_0_4/sim/ebaz4205_axis_capture_0_4.vhd" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_mult_gen_1_2/sim/ebaz4205_mult_gen_1_2.vhd" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_mult_gen_0_6/sim/ebaz4205_mult_gen_0_6.vhd" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_c_addsub_1_0/sim/ebaz4205_c_addsub_1_0.vhd" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_dds_compiler_0_4/sim/ebaz4205_dds_compiler_0_4.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_xlslice_0_6/sim/ebaz4205_xlslice_0_6.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_xlslice_0_7/sim/ebaz4205_xlslice_0_7.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_dds_axi_interface_0_5/sim/ebaz4205_dds_axi_interface_0_5.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_axis_mux_0_1/sim/ebaz4205_axis_mux_0_1.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_xlslice_1_2/sim/ebaz4205_xlslice_1_2.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_xlslice_0_8/sim/ebaz4205_xlslice_0_8.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_xlconstant_0_5/sim/ebaz4205_xlconstant_0_5.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_axi_gpio_0_6/sim/ebaz4205_axi_gpio_0_6.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work audio_formatter_v1_0_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/9554/hdl/audio_formatter_v1_0_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_audio_formatter_0_0/sim/ebaz4205_audio_formatter_0_0.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_clk_wiz_0_1/ebaz4205_clk_wiz_0_1_clk_wiz.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_clk_wiz_0_1/ebaz4205_clk_wiz_0_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work i2s_receiver_v1_0_5 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/9736/hdl/i2s_receiver_v1_0_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_i2s_receiver_0_0/sim/ebaz4205_i2s_receiver_0_0.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_proc_sys_reset_0_2/sim/ebaz4205_proc_sys_reset_0_2.vhd" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_proc_sys_reset_0_3/sim/ebaz4205_proc_sys_reset_0_3.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ebaz4205/sim/ebaz4205.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_s00_regslice_0/sim/ebaz4205_s00_regslice_0.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_s00_data_fifo_0/sim/ebaz4205_s00_data_fifo_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/aeb3/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_auto_pc_0/sim/ebaz4205_auto_pc_0.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_tier2_xbar_0_0/sim/ebaz4205_tier2_xbar_0_0.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_tier2_xbar_1_0/sim/ebaz4205_tier2_xbar_1_0.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_tier2_xbar_2_0/sim/ebaz4205_tier2_xbar_2_0.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_auto_pc_1/sim/ebaz4205_auto_pc_1.v" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_auto_pc_2/sim/ebaz4205_auto_pc_2.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/b8be/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/4675/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/7698" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/415b/hdl" +incdir+"$ref_dir/../../../../Vivado.gen/sources_1/bd/ebaz4205/ipshared/8713/hdl" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ebaz4205/ip/ebaz4205_auto_us_0/sim/ebaz4205_auto_us_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.ebaz4205 xil_defaultlib.glbl -o ebaz4205_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./ebaz4205_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./ebaz4205.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/guido/Github/EBAZ4205_SDR_spectrum/Vivado/Vivado.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key ebaz4205_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc ebaz4205_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./ebaz4205.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: ebaz4205.sh [-help]\n\
Usage: ebaz4205.sh [-lib_map_path]\n\
Usage: ebaz4205.sh [-reset_run]\n\
Usage: ebaz4205.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
