
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xnandps.h"

/*
* The configuration table for devices
*/

XNandPs_Config XNandPs_ConfigTable[XPAR_XNANDPS_NUM_INSTANCES] =
{
	{
		XPAR_PS7_NAND_0_DEVICE_ID,
		XPAR_PS7_NAND_0_SMC_BASEADDR,
		XPAR_PS7_NAND_0_BASEADDR,
		XPAR_PS7_NAND_0_NAND_WIDTH
	}
};


