# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/guido/Github/EBAZ4205_SDR_spectrum/ad9851gfsk/ad9851gfsk.srcs/sources_1/bd/ad9851gfsk_ip_v1_0_bfm_1/ip/ad9851gfsk_ip_v1_0_bfm_1_master_0_0/ad9851gfsk_ip_v1_0_bfm_1_master_0_0.xci
# IP: The module: 'ad9851gfsk_ip_v1_0_bfm_1_master_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/guido/Github/EBAZ4205_SDR_spectrum/ad9851gfsk/ad9851gfsk.gen/sources_1/bd/ad9851gfsk_ip_v1_0_bfm_1/ip/ad9851gfsk_ip_v1_0_bfm_1_master_0_0/ad9851gfsk_ip_v1_0_bfm_1_master_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ad9851gfsk_ip_v1_0_bfm_1_master_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/guido/Github/EBAZ4205_SDR_spectrum/ad9851gfsk/ad9851gfsk.srcs/sources_1/bd/ad9851gfsk_ip_v1_0_bfm_1/ip/ad9851gfsk_ip_v1_0_bfm_1_master_0_0/ad9851gfsk_ip_v1_0_bfm_1_master_0_0.xci
# IP: The module: 'ad9851gfsk_ip_v1_0_bfm_1_master_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/guido/Github/EBAZ4205_SDR_spectrum/ad9851gfsk/ad9851gfsk.gen/sources_1/bd/ad9851gfsk_ip_v1_0_bfm_1/ip/ad9851gfsk_ip_v1_0_bfm_1_master_0_0/ad9851gfsk_ip_v1_0_bfm_1_master_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ad9851gfsk_ip_v1_0_bfm_1_master_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
