# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ad9851gfsk_ip_v1_0_bfm_1/ad9851gfsk_ip_v1_0_bfm_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ad9851gfsk_ip_v1_0_bfm_1 || ORIG_REF_NAME==ad9851gfsk_ip_v1_0_bfm_1} -quiet] -quiet

# IP: bd/ad9851gfsk_ip_v1_0_bfm_1/ip/ad9851gfsk_ip_v1_0_bfm_1_master_0_0/ad9851gfsk_ip_v1_0_bfm_1_master_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ad9851gfsk_ip_v1_0_bfm_1_master_0_0 || ORIG_REF_NAME==ad9851gfsk_ip_v1_0_bfm_1_master_0_0} -quiet] -quiet

# IP: bd/ad9851gfsk_ip_v1_0_bfm_1/ip/ad9851gfsk_ip_v1_0_bfm_1_ad9851gfsk_0_0/ad9851gfsk_ip_v1_0_bfm_1_ad9851gfsk_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ad9851gfsk_ip_v1_0_bfm_1_ad9851gfsk_0_0 || ORIG_REF_NAME==ad9851gfsk_ip_v1_0_bfm_1_ad9851gfsk_0_0} -quiet] -quiet

# XDC: /home/guido/Github/EBAZ4205_SDR_spectrum/ad9851gfsk/ad9851gfsk.gen/sources_1/bd/ad9851gfsk_ip_v1_0_bfm_1/ad9851gfsk_ip_v1_0_bfm_1_ooc.xdc
