-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\AMdemod2\AM_Demodulator_pkg.vhd
-- Created: 2022-12-23 10:47:15
-- 
-- Generated by MATLAB 9.10 and HDL Coder 3.18
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE AM_Demodulator_pkg IS
  TYPE vector_of_unsigned7 IS ARRAY (NATURAL RANGE <>) OF unsigned(6 DOWNTO 0);
END AM_Demodulator_pkg;

