-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\AMdemod2\AM_Demodulator.vhd
-- Created: 2022-12-23 10:47:15
-- 
-- Generated by MATLAB 9.10 and HDL Coder 3.18
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 2.08333e-05
-- Target subsystem base rate: 1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out_AM_demod_16_bit           ce_out        1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: AM_Demodulator
-- Source Path: AMdemod2/AM Demodulator
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY AM_Demodulator IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        Out_AM_demod_16_bit               :   OUT   std_logic_vector(7 DOWNTO 0)  -- int8
        );
END AM_Demodulator;


ARCHITECTURE rtl OF AM_Demodulator IS

  -- Component Declarations
  COMPONENT Sqrt
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_48000_0                   :   IN    std_logic;
          din                             :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
          dout                            :   OUT   std_logic_vector(7 DOWNTO 0)  -- int8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Sqrt
    USE ENTITY work.Sqrt(rtl);

  -- Signals
  SIGNAL Constant_out1                    : signed(15 DOWNTO 0);  -- int16
  SIGNAL Sqrt_out1                        : std_logic_vector(7 DOWNTO 0);  -- ufix8

BEGIN
  u_Sqrt : Sqrt
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_48000_0 => clk_enable,
              din => std_logic_vector(Constant_out1),  -- int16
              dout => Sqrt_out1  -- int8
              );

  Constant_out1 <= to_signed(16#0001#, 16);

  ce_out <= clk_enable;

  Out_AM_demod_16_bit <= Sqrt_out1;

END rtl;

