-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\AMdemod_bis\AM_demod_pkg.vhd
-- Created: 2022-12-24 11:24:08
-- 
-- Generated by MATLAB 9.10 and HDL Coder 3.18
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE AM_demod_pkg IS
  TYPE vector_of_unsigned15 IS ARRAY (NATURAL RANGE <>) OF unsigned(14 DOWNTO 0);
END AM_demod_pkg;

