#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Apr 18 20:07:19 CEST 2023
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim ebaz4205_wrapper_func_synth -key {Post-Synthesis:sim_FT:Functional:ebaz4205_wrapper} -tclbatch ebaz4205_wrapper.tcl -protoinst "protoinst_files/ebaz4205.protoinst" -view /home/guido/GitHub/EBAZ4205_SDR_spectrum/Vivado/ebaz4205_wrapper_behav_FT.wcfg -log simulate.log"
xsim ebaz4205_wrapper_func_synth -key {Post-Synthesis:sim_FT:Functional:ebaz4205_wrapper} -tclbatch ebaz4205_wrapper.tcl -protoinst "protoinst_files/ebaz4205.protoinst" -view /home/guido/GitHub/EBAZ4205_SDR_spectrum/Vivado/ebaz4205_wrapper_behav_FT.wcfg -log simulate.log

