# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/ebaz4205.xdc

# Block Designs: bd/ebaz4205/ebaz4205.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205 || ORIG_REF_NAME==ebaz4205} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlslice_0_0/ebaz4205_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlslice_0_0 || ORIG_REF_NAME==ebaz4205_xlslice_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlconcat_0_0/ebaz4205_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlconcat_0_0 || ORIG_REF_NAME==ebaz4205_xlconcat_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlconstant_0_2/ebaz4205_xlconstant_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlconstant_0_2 || ORIG_REF_NAME==ebaz4205_xlconstant_0_2} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_DivideBy2N_0_0/ebaz4205_DivideBy2N_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_DivideBy2N_0_0 || ORIG_REF_NAME==ebaz4205_DivideBy2N_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_DivideBy4_25MHz_0/ebaz4205_DivideBy4_25MHz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_DivideBy4_25MHz_0 || ORIG_REF_NAME==ebaz4205_DivideBy4_25MHz_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_clk_wiz_0_0/ebaz4205_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_clk_wiz_0_0 || ORIG_REF_NAME==ebaz4205_clk_wiz_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_proc_sys_reset_0_0/ebaz4205_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_proc_sys_reset_0_0 || ORIG_REF_NAME==ebaz4205_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_proc_sys_reset_0_1/ebaz4205_proc_sys_reset_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_proc_sys_reset_0_1 || ORIG_REF_NAME==ebaz4205_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_processing_system7_0_0/ebaz4205_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_processing_system7_0_0 || ORIG_REF_NAME==ebaz4205_processing_system7_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_rst_ENET0_GMII_RX_CLK_0_100M_0/ebaz4205_rst_ENET0_GMII_RX_CLK_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_rst_ENET0_GMII_RX_CLK_0_100M_0 || ORIG_REF_NAME==ebaz4205_rst_ENET0_GMII_RX_CLK_0_100M_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_rst_ps7_0_140M_0/ebaz4205_rst_ps7_0_140M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_rst_ps7_0_140M_0 || ORIG_REF_NAME==ebaz4205_rst_ps7_0_140M_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_rst_ps7_0_64M_0/ebaz4205_rst_ps7_0_64M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_rst_ps7_0_64M_0 || ORIG_REF_NAME==ebaz4205_rst_ps7_0_64M_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlconcat_1_0/ebaz4205_xlconcat_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlconcat_1_0 || ORIG_REF_NAME==ebaz4205_xlconcat_1_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlconcat_2_0/ebaz4205_xlconcat_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlconcat_2_0 || ORIG_REF_NAME==ebaz4205_xlconcat_2_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_c_addsub_0_1/ebaz4205_c_addsub_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_c_addsub_0_1 || ORIG_REF_NAME==ebaz4205_c_addsub_0_1} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlslice_1_0/ebaz4205_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlslice_1_0 || ORIG_REF_NAME==ebaz4205_xlslice_1_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_dds_compiler_0_0/ebaz4205_dds_compiler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_dds_compiler_0_0 || ORIG_REF_NAME==ebaz4205_dds_compiler_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_dds_compiler_0_2/ebaz4205_dds_compiler_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_dds_compiler_0_2 || ORIG_REF_NAME==ebaz4205_dds_compiler_0_2} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_mult_gen_0_2/ebaz4205_mult_gen_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_mult_gen_0_2 || ORIG_REF_NAME==ebaz4205_mult_gen_0_2} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlconstant_2_3/ebaz4205_xlconstant_2_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlconstant_2_3 || ORIG_REF_NAME==ebaz4205_xlconstant_2_3} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlconstant_3_0/ebaz4205_xlconstant_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlconstant_3_0 || ORIG_REF_NAME==ebaz4205_xlconstant_3_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_dds_axi_interface_0_2/ebaz4205_dds_axi_interface_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_dds_axi_interface_0_2 || ORIG_REF_NAME==ebaz4205_dds_axi_interface_0_2} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_axi_gpio_1_0/ebaz4205_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_axi_gpio_1_0 || ORIG_REF_NAME==ebaz4205_axi_gpio_1_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlconstant_0_0/ebaz4205_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlconstant_0_0 || ORIG_REF_NAME==ebaz4205_xlconstant_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlconstant_1_0/ebaz4205_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlconstant_1_0 || ORIG_REF_NAME==ebaz4205_xlconstant_1_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlconstant_2_0/ebaz4205_xlconstant_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlconstant_2_0 || ORIG_REF_NAME==ebaz4205_xlconstant_2_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_axis_mux_0_0/ebaz4205_axis_mux_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_axis_mux_0_0 || ORIG_REF_NAME==ebaz4205_axis_mux_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_RF_test_1MHz_0/ebaz4205_RF_test_1MHz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_RF_test_1MHz_0 || ORIG_REF_NAME==ebaz4205_RF_test_1MHz_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlconstant_2_1/ebaz4205_xlconstant_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlconstant_2_1 || ORIG_REF_NAME==ebaz4205_xlconstant_2_1} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_dds_axi_interface_0_0/ebaz4205_dds_axi_interface_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_dds_axi_interface_0_0 || ORIG_REF_NAME==ebaz4205_dds_axi_interface_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlslice_sin_0/ebaz4205_xlslice_sin_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlslice_sin_0 || ORIG_REF_NAME==ebaz4205_xlslice_sin_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlslice_0_3/ebaz4205_xlslice_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlslice_0_3 || ORIG_REF_NAME==ebaz4205_xlslice_0_3} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_mult_gen_0_0/ebaz4205_mult_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_mult_gen_0_0 || ORIG_REF_NAME==ebaz4205_mult_gen_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_mult_sin_0/ebaz4205_mult_sin_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_mult_sin_0 || ORIG_REF_NAME==ebaz4205_mult_sin_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlslice_0_4/ebaz4205_xlslice_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlslice_0_4 || ORIG_REF_NAME==ebaz4205_xlslice_0_4} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_c_addsub_0_0/ebaz4205_c_addsub_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_c_addsub_0_0 || ORIG_REF_NAME==ebaz4205_c_addsub_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_mult_gen_0_1/ebaz4205_mult_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_mult_gen_0_1 || ORIG_REF_NAME==ebaz4205_mult_gen_0_1} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_mult_gen_1_0/ebaz4205_mult_gen_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_mult_gen_1_0 || ORIG_REF_NAME==ebaz4205_mult_gen_1_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_sqrt32_0_0/ebaz4205_sqrt32_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_sqrt32_0_0 || ORIG_REF_NAME==ebaz4205_sqrt32_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_cic_compiler_0_0/ebaz4205_cic_compiler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_cic_compiler_0_0 || ORIG_REF_NAME==ebaz4205_cic_compiler_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_fir_compiler_0_0/ebaz4205_fir_compiler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_fir_compiler_0_0 || ORIG_REF_NAME==ebaz4205_fir_compiler_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_mult_gen_0_3/ebaz4205_mult_gen_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_mult_gen_0_3 || ORIG_REF_NAME==ebaz4205_mult_gen_0_3} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_axi_interface_DEC_RATE_Q_0/ebaz4205_axi_interface_DEC_RATE_Q_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_axi_interface_DEC_RATE_Q_0 || ORIG_REF_NAME==ebaz4205_axi_interface_DEC_RATE_Q_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_axi_gpio_0_1/ebaz4205_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_axi_gpio_0_1 || ORIG_REF_NAME==ebaz4205_axi_gpio_0_1} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_axis2c_splitter_0_0/ebaz4205_axis2c_splitter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_axis2c_splitter_0_0 || ORIG_REF_NAME==ebaz4205_axis2c_splitter_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_axis2c_splitter_0_1/ebaz4205_axis2c_splitter_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_axis2c_splitter_0_1 || ORIG_REF_NAME==ebaz4205_axis2c_splitter_0_1} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_axis2c_combine_0_0/ebaz4205_axis2c_combine_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_axis2c_combine_0_0 || ORIG_REF_NAME==ebaz4205_axis2c_combine_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlconcat_0_2/ebaz4205_xlconcat_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlconcat_0_2 || ORIG_REF_NAME==ebaz4205_xlconcat_0_2} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlconstant_1_1/ebaz4205_xlconstant_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlconstant_1_1 || ORIG_REF_NAME==ebaz4205_xlconstant_1_1} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_DivideBy10_0/ebaz4205_DivideBy10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_DivideBy10_0 || ORIG_REF_NAME==ebaz4205_DivideBy10_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_I2S_Transmitter_0_2/ebaz4205_I2S_Transmitter_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_I2S_Transmitter_0_2 || ORIG_REF_NAME==ebaz4205_I2S_Transmitter_0_2} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_axi_dynclk_0_0/ebaz4205_axi_dynclk_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_axi_dynclk_0_0 || ORIG_REF_NAME==ebaz4205_axi_dynclk_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_axi_vdma_0_0/ebaz4205_axi_vdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_axi_vdma_0_0 || ORIG_REF_NAME==ebaz4205_axi_vdma_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_axis_subset_converter_0_0/ebaz4205_axis_subset_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_axis_subset_converter_0_0 || ORIG_REF_NAME==ebaz4205_axis_subset_converter_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_v_tc_0_0/ebaz4205_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_v_tc_0_0 || ORIG_REF_NAME==ebaz4205_v_tc_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlconstant_0_3/ebaz4205_xlconstant_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlconstant_0_3 || ORIG_REF_NAME==ebaz4205_xlconstant_0_3} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlconcat_0_3/ebaz4205_xlconcat_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlconcat_0_3 || ORIG_REF_NAME==ebaz4205_xlconcat_0_3} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_axi_interconnect_0_2/ebaz4205_axi_interconnect_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_axi_interconnect_0_2 || ORIG_REF_NAME==ebaz4205_axi_interconnect_0_2} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_v_axi4s_vid_out_0_1/ebaz4205_v_axi4s_vid_out_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_v_axi4s_vid_out_0_1 || ORIG_REF_NAME==ebaz4205_v_axi4s_vid_out_0_1} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_rgb2dvi_0_3/ebaz4205_rgb2dvi_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_rgb2dvi_0_3 || ORIG_REF_NAME==ebaz4205_rgb2dvi_0_3} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_axi_gpio_0_2/ebaz4205_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_axi_gpio_0_2 || ORIG_REF_NAME==ebaz4205_axi_gpio_0_2} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xbar_0/ebaz4205_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xbar_0 || ORIG_REF_NAME==ebaz4205_xbar_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_axi_interconnect_0_0/ebaz4205_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_axi_interconnect_0_0 || ORIG_REF_NAME==ebaz4205_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_mult_gen_0_4/ebaz4205_mult_gen_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_mult_gen_0_4 || ORIG_REF_NAME==ebaz4205_mult_gen_0_4} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_mult_gen_1_1/ebaz4205_mult_gen_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_mult_gen_1_1 || ORIG_REF_NAME==ebaz4205_mult_gen_1_1} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlslice_0_5/ebaz4205_xlslice_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlslice_0_5 || ORIG_REF_NAME==ebaz4205_xlslice_0_5} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlslice_1_1/ebaz4205_xlslice_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlslice_1_1 || ORIG_REF_NAME==ebaz4205_xlslice_1_1} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlslice_2_0/ebaz4205_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlslice_2_0 || ORIG_REF_NAME==ebaz4205_xlslice_2_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_dds_axi_interface_0_3/ebaz4205_dds_axi_interface_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_dds_axi_interface_0_3 || ORIG_REF_NAME==ebaz4205_dds_axi_interface_0_3} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_dds_compiler_0_3/ebaz4205_dds_compiler_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_dds_compiler_0_3 || ORIG_REF_NAME==ebaz4205_dds_compiler_0_3} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlconstant_0_4/ebaz4205_xlconstant_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlconstant_0_4 || ORIG_REF_NAME==ebaz4205_xlconstant_0_4} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_dds_axi_interface_0_4/ebaz4205_dds_axi_interface_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_dds_axi_interface_0_4 || ORIG_REF_NAME==ebaz4205_dds_axi_interface_0_4} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_cic_compiler_0_1/ebaz4205_cic_compiler_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_cic_compiler_0_1 || ORIG_REF_NAME==ebaz4205_cic_compiler_0_1} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_fir_compiler_0_1/ebaz4205_fir_compiler_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_fir_compiler_0_1 || ORIG_REF_NAME==ebaz4205_fir_compiler_0_1} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_axi_gpio_0_5/ebaz4205_axi_gpio_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_axi_gpio_0_5 || ORIG_REF_NAME==ebaz4205_axi_gpio_0_5} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_mult_gen_0_5/ebaz4205_mult_gen_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_mult_gen_0_5 || ORIG_REF_NAME==ebaz4205_mult_gen_0_5} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_axis_capture_0_5/ebaz4205_axis_capture_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_axis_capture_0_5 || ORIG_REF_NAME==ebaz4205_axis_capture_0_5} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_xlconcat_0_4/ebaz4205_xlconcat_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_xlconcat_0_4 || ORIG_REF_NAME==ebaz4205_xlconcat_0_4} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_axis2c_splitter_0_2/ebaz4205_axis2c_splitter_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_axis2c_splitter_0_2 || ORIG_REF_NAME==ebaz4205_axis2c_splitter_0_2} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_axis2c_combine_0_1/ebaz4205_axis2c_combine_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_axis2c_combine_0_1 || ORIG_REF_NAME==ebaz4205_axis2c_combine_0_1} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_axi_gpio_0_4/ebaz4205_axi_gpio_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_axi_gpio_0_4 || ORIG_REF_NAME==ebaz4205_axi_gpio_0_4} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_ps2_mouse_0_0/ebaz4205_ps2_mouse_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_ps2_mouse_0_0 || ORIG_REF_NAME==ebaz4205_ps2_mouse_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_util_vector_logic_0_1/ebaz4205_util_vector_logic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_util_vector_logic_0_1 || ORIG_REF_NAME==ebaz4205_util_vector_logic_0_1} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_axi_gpio_0_3/ebaz4205_axi_gpio_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_axi_gpio_0_3 || ORIG_REF_NAME==ebaz4205_axi_gpio_0_3} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_axis_capture_0_4/ebaz4205_axis_capture_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_axis_capture_0_4 || ORIG_REF_NAME==ebaz4205_axis_capture_0_4} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_AXI_Stream_Generator_0_0/ebaz4205_AXI_Stream_Generator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_AXI_Stream_Generator_0_0 || ORIG_REF_NAME==ebaz4205_AXI_Stream_Generator_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_axis2c_splitter_0_3/ebaz4205_axis2c_splitter_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_axis2c_splitter_0_3 || ORIG_REF_NAME==ebaz4205_axis2c_splitter_0_3} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_reset_lengthener_0_0/ebaz4205_reset_lengthener_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_reset_lengthener_0_0 || ORIG_REF_NAME==ebaz4205_reset_lengthener_0_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_s00_regslice_0/ebaz4205_s00_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_s00_regslice_0 || ORIG_REF_NAME==ebaz4205_s00_regslice_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_s00_data_fifo_0/ebaz4205_s00_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_s00_data_fifo_0 || ORIG_REF_NAME==ebaz4205_s00_data_fifo_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_auto_pc_0/ebaz4205_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_auto_pc_0 || ORIG_REF_NAME==ebaz4205_auto_pc_0} -quiet] -quiet

# IP: bd/ebaz4205/ip/ebaz4205_auto_pc_1/ebaz4205_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz4205_auto_pc_1 || ORIG_REF_NAME==ebaz4205_auto_pc_1} -quiet] -quiet

# XDC: /home/guido/GitHub/EBAZ4205_SDR_spectrum/Vivado/Vivado.gen/sources_1/bd/ebaz4205/ebaz4205_ooc.xdc
