# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/guido/GitHub/EBAZ4205_SDR_spectrum/Vivado/Vivado.srcs/sources_1/bd/ebaz4205/ip/ebaz4205_fir_compiler_0_1/ebaz4205_fir_compiler_0_1.xci
# IP: The module: 'ebaz4205_fir_compiler_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/guido/GitHub/EBAZ4205_SDR_spectrum/Vivado/Vivado.gen/sources_1/bd/ebaz4205/ip/ebaz4205_fir_compiler_0_1/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'ebaz4205_fir_compiler_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/guido/GitHub/EBAZ4205_SDR_spectrum/Vivado/Vivado.gen/sources_1/bd/ebaz4205/ip/ebaz4205_fir_compiler_0_1/ebaz4205_fir_compiler_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ebaz4205_fir_compiler_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/guido/GitHub/EBAZ4205_SDR_spectrum/Vivado/Vivado.srcs/sources_1/bd/ebaz4205/ip/ebaz4205_fir_compiler_0_1/ebaz4205_fir_compiler_0_1.xci
# IP: The module: 'ebaz4205_fir_compiler_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/guido/GitHub/EBAZ4205_SDR_spectrum/Vivado/Vivado.gen/sources_1/bd/ebaz4205/ip/ebaz4205_fir_compiler_0_1/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'ebaz4205_fir_compiler_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/guido/GitHub/EBAZ4205_SDR_spectrum/Vivado/Vivado.gen/sources_1/bd/ebaz4205/ip/ebaz4205_fir_compiler_0_1/ebaz4205_fir_compiler_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ebaz4205_fir_compiler_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
