
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_ADC_TESTGEN_TESTGEN_AXI_GPIO_ADC_TEST_DEVICE_ID,
		XPAR_ADC_TESTGEN_TESTGEN_AXI_GPIO_ADC_TEST_BASEADDR,
		XPAR_ADC_TESTGEN_TESTGEN_AXI_GPIO_ADC_TEST_INTERRUPT_PRESENT,
		XPAR_ADC_TESTGEN_TESTGEN_AXI_GPIO_ADC_TEST_IS_DUAL
	},
	{
		XPAR_FILTER_AXI_GPIO_FILTER_GAIN_DEVICE_ID,
		XPAR_FILTER_AXI_GPIO_FILTER_GAIN_BASEADDR,
		XPAR_FILTER_AXI_GPIO_FILTER_GAIN_INTERRUPT_PRESENT,
		XPAR_FILTER_AXI_GPIO_FILTER_GAIN_IS_DUAL
	},
	{
		XPAR_HDMI_AXI_GPIO_HDMI_DEVICE_ID,
		XPAR_HDMI_AXI_GPIO_HDMI_BASEADDR,
		XPAR_HDMI_AXI_GPIO_HDMI_INTERRUPT_PRESENT,
		XPAR_HDMI_AXI_GPIO_HDMI_IS_DUAL
	},
	{
		XPAR_HDMI_AXI_GPIO_0_DEVICE_ID,
		XPAR_HDMI_AXI_GPIO_0_BASEADDR,
		XPAR_HDMI_AXI_GPIO_0_INTERRUPT_PRESENT,
		XPAR_HDMI_AXI_GPIO_0_IS_DUAL
	}
};


