#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Sep 20 11:08:46 CEST 2023
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim ad9851gfsk_ip_v1_0_tb_behav -key {Behavioral:sim_1:Functional:ad9851gfsk_ip_v1_0_tb} -tclbatch ad9851gfsk_ip_v1_0_tb.tcl -protoinst "protoinst_files/ad9851gfsk_ip_v1_0_bfm_1.protoinst" -view /home/guido/Github/EBAZ4205_SDR_spectrum/ad9851gfsk/ad9851gfsk_ip_v1_0_tb_behav.wcfg -log simulate.log"
xsim ad9851gfsk_ip_v1_0_tb_behav -key {Behavioral:sim_1:Functional:ad9851gfsk_ip_v1_0_tb} -tclbatch ad9851gfsk_ip_v1_0_tb.tcl -protoinst "protoinst_files/ad9851gfsk_ip_v1_0_bfm_1.protoinst" -view /home/guido/Github/EBAZ4205_SDR_spectrum/ad9851gfsk/ad9851gfsk_ip_v1_0_tb_behav.wcfg -log simulate.log

